site_name: STEM Classroom Administration with AI
site_description: 'This GitHub repo helps teachers learn to use AI to setup and administer a STEM classroom with a focus on teaching computational thinking using physical computing and microcontrollers.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/stem-classroom-admin/'
repo_url: 'https://github.com/dmccreary/stem-classroom-admin'
edit_uri: 'blob/master/docs'

nav:
  - Home: index.md
  - About: about.md
  - Concepts:
    - Introduction: concepts/index.md
    - USB Port Administration: concepts/usb-port-administration.md
    - USB Power Draw: concepts/usb-power-draw.md
  - Chromebook:
    - Developer Mode: chromebook/developer-mode.md
    - Setting Up Developer Mode: chromebook/setting-up-developer-mode.md
    - Thonny Admin: chromebook/thonny-admin.md
  - MacOS:
    - Intro: macos/index.md             

             - chromebook/index.md
             - macos/usb-ports.md

  - Windows:
    - Intro: windows/index.md
    - Thonny Admin: windows/thonny-admin.md
  - Linux:
    - linux/index.md
  - USB Debug: usb-debug.md
  - Glossary: glossary.md
  - How We Built This Site: how-we-built-this-site.md
  - References: references.md
  - License: license.md
  - Contact: contact.md
 
# CoderDojo Microsite Standards from here down

theme:
  name: material
  extra_css:
    - styles/custom.css
  logo: img/logo.png
  favicon: img/favicon.ico
  palette:
    primary: 'blue'
    accent: 'orange'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
    - content.action.edit
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra_css:
   - css/extra.css
#extra:
#  analytics:
#    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-XXXX